services:
  db:
    image: postgres:14.18-alpine3.22
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    image: whalesdmtr/expense_tracker-app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend

volumes:
  db-data:


networks:
  backend:
